Matrix Decompostion

In [2]:
import numpy as np
np.printoptions(precision=4,supress=True)

A=LU decmposition

In [8]:
import scipy.linalg as lu
A=np.array([
    [4,3],
    [6,3],
    [8,5]
])
P,L,U=lu.lu(A)
print("P:\n",P)
print("L:\n",L) 
print("U:\n",U)
print("Reconstructed A:\n",P@L@U)

P:
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
L:
 [[ 1.          0.        ]
 [ 0.75        1.        ]
 [ 0.5        -0.66666667]]
U:
 [[ 8.    5.  ]
 [ 0.   -0.75]]
Reconstructed A:
 [[4. 3.]
 [6. 3.]
 [8. 5.]]


In [11]:
import scipy.linalg as lu
A=np.array([
    [0,2],
    [6,3],
    
])
P,L,U=lu.lu(A)
print("P:\n",P)
print("L:\n",L) 
print("U:\n",U)
print("Reconstructed A:\n",P@L@U)

P:
 [[0. 1.]
 [1. 0.]]
L:
 [[1. 0.]
 [0. 1.]]
U:
 [[6. 3.]
 [0. 2.]]
Reconstructed A:
 [[0. 2.]
 [6. 3.]]


Gram schmidt

In [12]:
A=np.array([[4, 3], [6, 3]])
Q,R=np.linalg.qr(A)
print("Q:\n",Q)
print("R:\n",R)
print("Reconstructed A:\n",Q@R)

Q:
 [[-0.5547002  -0.83205029]
 [-0.83205029  0.5547002 ]]
R:
 [[-7.21110255 -4.16025147]
 [ 0.         -0.83205029]]
Reconstructed A:
 [[4. 3.]
 [6. 3.]]


Least square

In [15]:
A=np.array([[4, 3], [6, 3]])
b=np.array([10,12])

Q,R=lu.qr(A)
y=np.linalg.solve(R,Q.T@b)
print("Solution x:\n",y)
y_np,*_=np.linalg.lstsq(A,b,rcond=None)
print("Numpy lstsq Solution x:\n",y_np)


Solution x:
 [1. 2.]
Numpy lstsq Solution x:
 [1. 2.]


Eigen value

In [17]:
#eigen values and vectors
A=np.array([[4, -2], [1, 1]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:\n",eigenvalues)
print("Eigenvectors:\n",eigenvectors)
print("A v:",A @ eigenvectors[:,0])
print("λ v:",eigenvalues[0] * eigenvectors[:,0])

Eigenvalues:
 [3. 2.]
Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]
A v: [2.68328157 1.34164079]
λ v: [2.68328157 1.34164079]


Symettric matric eigen value

In [18]:
#eigen value and vector of symmetric matrix
A=np.array([[4, 2], [2, 3]])
eigenvalues, eigenvectors = np.linalg.eigh(A)
print("Eigenvalues:\n",eigenvalues) 
print("Eigenvectors:\n",eigenvectors)


Eigenvalues:
 [1.43844719 5.56155281]
Eigenvectors:
 [[ 0.61541221 -0.78820544]
 [-0.78820544 -0.61541221]]


Positive definite

In [22]:
def positie_definite(A):
    try:
        np.linalg.cholesky(A)
        return True
    except np.linalg.LinAlgError:
        return False
    
A=np.array([[4, 2], [2, 3]])
e,ev=np.linalg.eig(A)
print("Eigenvalues:",e)
if np.all(e>0):
    print("All eigenvalues are positive.")  
print("Is A positive definite?",positie_definite(A))

Eigenvalues: [5.56155281 1.43844719]
All eigenvalues are positive.
Is A positive definite? True


Single value decompostion

In [24]:
#svd and rank ,single values,null space
A=np.array([[4, 3], [6, 3]])
U,S,Vt=np.linalg.svd(A)
print("U:\n",U)
print("S:\n",S)
print("Vt:\n",Vt)
print("Reconstructed A:\n",U @ np.diag(S) @ Vt)
print("Rank of A:",np.linalg.matrix_rank(A))
print("Null space of A:",Vt.T[:,2-1:])  #last column of Vt transposed

U:
 [[-0.59581566 -0.80312122]
 [-0.80312122  0.59581566]]
S:
 [8.33557912 0.71980602]
Vt:
 [[-0.86400595 -0.50348159]
 [ 0.50348159 -0.86400595]]
Reconstructed A:
 [[4. 3.]
 [6. 3.]]
Rank of A: 2
Null space of A: [[ 0.50348159]
 [-0.86400595]]
