Norms and orhogonality


In [1]:
import numpy as np

Types of norms(manhatten,eucliedion,infinity)

In [4]:
x=np.array([3,-4])
l1=np.linalg.norm(x,ord=1)
l2=np.linalg.norm(x,ord=2)
l8=np.linalg.norm(x,ord=np.inf)
print("L1 norm:", l1)
print("L2 norm:", l2)
print("L-infinity norm:", l8)

L1 norm: 7.0
L2 norm: 5.0
L-infinity norm: 4.0


Unit vector

In [5]:
x=np.array([8,4,5])
unit_x=x/np.linalg.norm(x)
print("Unit vector in the direction of x:", unit_x)
print("Norm of the unit vector:", np.linalg.norm(unit_x))

Unit vector in the direction of x: [0.78072006 0.39036003 0.48795004]
Norm of the unit vector: 1.0


Inner product & Angles

In [6]:
x=np.array([1, 2, 3])
y=np.array([4, 5, 6])
dot=np.dot(x,y)
angle=np.arccos(dot/(np.linalg.norm(x)*np.linalg.norm(y)))
print("Dot product of x and y:", dot)
print("Angle between x and y (in radians):", angle)


Dot product of x and y: 32
Angle between x and y (in radians): 0.2257261285527342


projection fo vector

In [7]:
x=np.array([1, 2, 3])
u=np.array([2,1,-2])
proj=(np.dot(x,u)/np.dot(u,u))*u
print("Projection of x onto u:", proj)


Projection of x onto u: [-0.44444444 -0.22222222  0.44444444]


Projection onto the subspce

In [8]:
u=np.array([1,0,0])
v=np.array([0,1,0])
u=u/np.linalg.norm(u)
proj=(np.dot(v,u))*u
orthogonal_component=v - proj   
print("Orthogonal component of v relative to u:", orthogonal_component)
print("proj + orthogonal_component equals v:", np.allclose(proj + orthogonal_component, v))

Orthogonal component of v relative to u: [0. 1. 0.]
proj + orthogonal_component equals v: True


Projection matrix p=b bT

In [12]:
b = np.array([1, 1, 1], dtype=float).reshape(-1, 1)
b = b / np.linalg.norm(b)

P = b @ b.T

x = np.array([3, 4, 5])

proj = P @ x
print(proj)
orthogonal_component=x - proj
print("Orthogonal component of x relative to b:", orthogonal_component)

[4. 4. 4.]
Orthogonal component of x relative to b: [-1.0000000e+00 -8.8817842e-16  1.0000000e+00]


gram schmidt specializtion

In [13]:
def gram_schmidt(vectors):
    orthonormal_basis = []
    for v in vectors:
        for u in orthonormal_basis:
            v = v - np.dot(v, u) * u
        v = v / np.linalg.norm(v)
        orthonormal_basis.append(v)
    return np.array(orthonormal_basis)

vectors = [np.array([1, 1, 0]), np.array([1, 0, 1]), np.array([0, 1, 1])]
orthonormal_basis = gram_schmidt(vectors)
print("Orthonormal basis:\n", orthonormal_basis)

Orthonormal basis:
 [[ 0.70710678  0.70710678  0.        ]
 [ 0.40824829 -0.40824829  0.81649658]
 [-0.57735027  0.57735027  0.57735027]]


Distance point from subspace

In [14]:
x=np.array([1,2,3])
u=np.array([4,5,6])
proj=(np.dot(x,u)/np.dot(u,u))*u
print("Projection of x onto u:", proj)
distance=np.linalg.norm(x-proj)
print("Distance from x to the line spanned by u:", distance)

Projection of x onto u: [1.66233766 2.07792208 2.49350649]
Distance from x to the line spanned by u: 0.837435789358624


Pca small version

In [15]:
x=np.array([[1,1,],[11,2],[3,3],[6,5],[5,4]],dtype=float)
# mini pca
x_meaned=x-np.mean(x,axis=0)
cov_mat=np.cov(x_meaned,rowvar=False)
eigen_values,eigen_vectors=np.linalg.eigh(cov_mat)
print("Eigenvalues:\n", eigen_values)
print("Eigenvectors:\n", eigen_vectors)
print("covariance matrix:\n", cov_mat)



Eigenvalues:
 [ 2.41514533 14.28485467]
Eigenvectors:
 [[ 0.08455082 -0.99641917]
 [-0.99641917 -0.08455082]]
covariance matrix:
 [[14.2  1. ]
 [ 1.   2.5]]
