Vector Calculus

LOSS  l(w)=||Ax-b||^2

In [4]:
import numpy as np
np.set_printoptions(precision=4,suppress=True)
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[9,8,7],[6,5,4],[3,2,1]])
def loss_function(w):
    return np.sum((A@w - B)**2)
t=np.array([1,1,1])
print("Loss:", loss_function(t))


Loss: 1554


GRadient

In [5]:
import numpy as np
np.set_printoptions(precision=4,suppress=True)
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[9,8,7],[6,5,4],[3,2,1]])
def gradient_loss_function(w):
    return 2*A.T@(A@w - B)
t=np.array([1,1,1])
print("Gradient of Loss:", gradient_loss_function(t))

Gradient of Loss: [[ 36 276 516]
 [ 36 336 636]
 [ 36 396 756]]


In [6]:
#solve by putting gradient to zero
A_T_A=np.dot(A.T,A)
A_T_B=np.dot(A.T,B)
w_optimal=np.linalg.solve(A_T_A,A_T_B)
print("Optimal w:\n",w_optimal)
print("Loss at optimal w:", loss_function(w_optimal))


Optimal w:
 [[-6.  -6.  -5.5]
 [-0.   1.   1. ]
 [ 5.   4.   3.5]]
Loss at optimal w: 9.624103043696344e-28


In [8]:
import numpy as np
np.set_printoptions(precision=4,suppress=True)
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[9,8,7],[6,5,4],[3,2,1]])
def gradient_loss_function(w):
    return 2*A.T@(A@w - B)
t=np.array([1,1,1])
print("Gradient of Loss:", gradient_loss_function(t))
w_np, *_ = np.linalg.lstsq(A, B, rcond=None)
print("w* (np.linalg.lstsq):", w_np)


Gradient of Loss: [[ 36 276 516]
 [ 36 336 636]
 [ 36 396 756]]
w* (np.linalg.lstsq): [[-5.8333 -5.3333 -4.8333]
 [-0.3333 -0.3333 -0.3333]
 [ 5.1667  4.6667  4.1667]]


In [15]:
import numpy as np
np.set_printoptions(precision=4,suppress=True)
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[9,8,7],[6,5,4],[3,2,1]])
def gradient_loss_function(w):
    return 2*A.T@(A@w - B)
def loss_function(w):
    return np.sum((A@w - B)**2)
w_np, *_ = np.linalg.lstsq(A, B, rcond=None)
print("w* (np.linalg.lstsq):", w_np)

lr = 0.01  # Define learning rate
w = np.zeros((3,3))  # Initialize w as 3x3 array
for i in range(50):
    w = w  - lr * gradient_loss_function(w)
print("Loss after GD:", loss_function(w))
print("w after GD:", w)
H = 2 * A.T @ A
print("Hessian:\n", H)
print("Eigenvalues of Hessian:", np.linalg.eigvals(H))



w* (np.linalg.lstsq): [[-5.8333 -5.3333 -4.8333]
 [-0.3333 -0.3333 -0.3333]
 [ 5.1667  4.6667  4.1667]]
Loss after GD: 1.115260781677637e+69
w after GD: [[-6.7718e+32 -5.3684e+32 -3.9650e+32]
 [-8.0804e+32 -6.4059e+32 -4.7313e+32]
 [-9.3891e+32 -7.4433e+32 -5.4975e+32]]
Hessian:
 [[132 156 180]
 [156 186 216]
 [180 216 252]]
Eigenvalues of Hessian: [567.7172   2.2828   0.    ]
